"""Transparent aggregated patterns representing 138 fictional troubleshooting cases."""

from ai_server_te_workbench.conversation.matcher import match_issue
from ai_server_te_workbench.knowledge.models import (
    PatternMatch,
    SymptomCategory as C,
    SyntheticCasePattern,
)


def synthetic_case_patterns() -> tuple[SyntheticCasePattern, ...]:
    return (
        _p(
            "bmc_single_dut_timeout",
            "單台 BMC timeout",
            "同一個 port 其他機器正常，只有這台 BMC timeout",
            C.NETWORK_UNREACHABLE,
            ("bmc", "timeout", "只有這台", "其他機器正常"),
            ("single DUT", "golden passes", "BMC path"),
            "先在同一 cable／port 驗證 Golden Sample。",
            "correct_bmc_config",
            "修正 BMC IP、VLAN 或 service 設定後重測。",
            12,
            10,
        ),
        _p(
            "station_all_units_offline",
            "同站所有機器都無法連線",
            "這個 station 換了三台都 ping 不到",
            C.NETWORK_UNREACHABLE,
            ("都連不上", "所有機器", "station", "ping 不到"),
            ("multiple DUTs", "same station", "shared failure"),
            "用 Golden Sample 確認 station cable、port 與 VLAN。",
            "restore_station_network_path",
            "修復 station switch port、VLAN 或 cable path。",
            9,
            8,
        ),
        _p(
            "physical_link_down",
            "更換 cable 後 link 恢復",
            "網路孔沒有 link light，換線後正常",
            C.NETWORK_UNREACHABLE,
            ("link light", "link down", "換線", "cable"),
            ("physical link down", "known-good cable available"),
            "交換 known-good cable 與 switch port。",
            "replace_network_cable",
            "更換不良 cable 或修復實體 port path。",
            7,
            7,
        ),
        _p(
            "duplicate_ip_intermittent",
            "IP conflict 造成間歇斷線",
            "BMC 有時連得到有時 timeout，懷疑 IP 重複",
            C.NETWORK_UNREACHABLE,
            ("間歇", "有時", "ip conflict", "ip 重複"),
            ("intermittent", "link up", "address conflict"),
            "核對 ARP、租約與 approved BMC IP。",
            "remove_duplicate_ip",
            "移除重複 IP 並重新驗證連線穩定性。",
            6,
            5,
        ),
        _p(
            "vlan_after_station_move",
            "換站後 VLAN 不一致",
            "server 換到另一站後 BMC 就連不上",
            C.NETWORK_UNREACHABLE,
            ("換站", "另一站", "vlan", "移動"),
            ("worked before move", "new station"),
            "比較新舊 station 的 VLAN 與 switch port profile。",
            "restore_vlan_profile",
            "套用 approved VLAN／port profile。",
            5,
            4,
        ),
        _p(
            "failure_follows_dut",
            "問題跟著 DUT 到第二站",
            "這台不行但另一台可以，換 station 還是一樣",
            C.ONE_UNIT_ONLY,
            ("這台不行", "另一台可以", "換 station", "還是一樣"),
            ("golden passes", "cross-station reproduces"),
            "執行 Golden Sample 與 cross-station A/B swap。",
            "isolate_dut_with_swap",
            "完成 DUT-path isolation 並依失敗 test case 升級。",
            8,
            6,
        ),
        _p(
            "failure_stays_station",
            "問題留在原 station",
            "失敗機到另一站會過，Golden 在原站也失敗",
            C.ONE_UNIT_ONLY,
            ("另一站會過", "原站", "golden", "也失敗"),
            ("DUT passes elsewhere", "golden fails original station"),
            "先修復原 fixture／environment／test program。",
            "repair_station_path",
            "修復 station path 後用 Golden Sample 驗證。",
            6,
            5,
        ),
        _p(
            "firmware_after_update",
            "更新後 firmware baseline 不符",
            "更新 firmware 後測試版本不符合 golden baseline",
            C.FIRMWARE_MISMATCH,
            ("更新後", "firmware", "版本不符", "baseline"),
            ("post-update", "checksum mismatch"),
            "比對 approved image checksum、版本與設定。",
            "restore_approved_firmware",
            "依核准流程恢復 firmware image 與設定。",
            5,
            5,
        ),
        _p(
            "gpu_count_seven_of_eight",
            "預期 8 張只辨識 7 張 GPU",
            "lspci 只看到 7/8 張 GPU",
            C.GPU_MISSING,
            ("7/8", "gpu", "少一張", "lspci"),
            ("one GPU missing", "persistent after cold restart"),
            "先 cold restart 並核對 power state，再安全斷電檢查。",
            "recheck_gpu_power_and_seating",
            "由合格人員處理 GPU seating／power 後重測。",
            4,
            3,
        ),
        _p(
            "gpu_recovers_cold_restart",
            "Cold restart 後 GPU 恢復",
            "warm reboot 少 GPU，完全斷電再開就恢復",
            C.GPU_MISSING,
            ("warm reboot", "cold restart", "斷電", "恢復"),
            ("warm-only failure", "cold restart recovers"),
            "比較 warm reboot 與 cold restart enumeration。",
            "recover_gpu_enumeration",
            "記錄 power-state 相關間歇問題並升級 firmware 分析。",
            3,
            3,
        ),
        _p(
            "airflow_obstruction",
            "Airflow obstruction 導致高溫",
            "idle 溫度過高而且風扇進風被擋住",
            C.TEMPERATURE_HIGH,
            ("idle", "溫度過高", "airflow", "風扇"),
            ("high at idle", "airflow abnormal"),
            "在 approved idle condition 檢查 fan 與 airflow。",
            "restore_airflow",
            "清除 airflow obstruction 並以相同條件重測。",
            4,
            4,
        ),
        _p(
            "load_dependent_temperature",
            "Workload 條件造成溫度差異",
            "壓力測試才高溫，idle 正常",
            C.TEMPERATURE_HIGH,
            ("壓力測試", "高溫", "idle 正常", "workload"),
            ("load dependent", "idle normal"),
            "先對齊 workload、sensor 與 temperature limit。",
            "normalize_test_load",
            "對齊 test load 與判定條件後重新量測。",
            3,
            2,
        ),
        _p(
            "no_power_bad_pdu_path",
            "按電源沒有反應，PDU path 異常",
            "按下 power button 沒有 LED 或風扇，Golden 換到同一個 PDU outlet 也不能上電",
            C.POWER_OR_POST_FAILURE,
            ("按下", "沒有 led", "不能上電", "pdu", "power button"),
            ("no power response", "golden also fails", "shared PDU path"),
            "先用 Golden Sample 與 approved power cable 驗證外部供電路徑。",
            "restore_external_power_path",
            "修復 PDU outlet 或 approved power cable 後重新上電。",
            8,
            6,
        ),
        _p(
            "post_stuck_after_config_change",
            "變更配置後卡在 POST",
            "更換測試配置後 server 有上電但一直卡在 POST code",
            C.POWER_OR_POST_FAILURE,
            ("配置後", "卡在 post", "post code", "有上電"),
            ("power on", "POST incomplete", "configuration changed"),
            "記錄最後 POST code 並比對 approved BOM 與 firmware baseline。",
            "align_post_baseline",
            "恢復核准配置後以相同 console 觀察 POST。",
            6,
            5,
        ),
        _p(
            "power_cycle_shutdown",
            "上電後數秒自行關機",
            "server 開機幾秒後自己斷電，PSU LED 曾經亮起",
            C.POWER_OR_POST_FAILURE,
            ("幾秒後", "自己斷電", "psu led", "自行關機"),
            ("brief power on", "unexpected shutdown", "PSU evidence"),
            "先排除共用供電路徑並保存 BMC power event log。",
            "restore_external_power_path",
            "處理外部供電 path；若問題跟著 DUT 則攜帶 event log 升級。",
            5,
            3,
        ),
        _p(
            "dimm_inventory_missing",
            "DIMM inventory 少一條",
            "BIOS 顯示記憶體少一條，容量也低於 approved BOM",
            C.MEMORY_ERROR,
            ("記憶體少一條", "容量", "approved bom", "bios"),
            ("DIMM inventory mismatch", "capacity reduced"),
            "Cold restart 後比對 BIOS／BMC DIMM inventory 與 population rule。",
            "restore_memory_configuration",
            "對齊 configuration 或由合格人員處理 DIMM seating 後重測。",
            7,
            6,
        ),
        _p(
            "ecc_error_repeated",
            "相同 DIMM 重複出現 ECC error",
            "壓力測試時同一個 DIMM slot 一直出現 ECC error",
            C.MEMORY_ERROR,
            ("dimm slot", "ecc error", "一直出現", "壓力測試"),
            ("repeated ECC", "same slot", "under load"),
            "保存 ECC address／slot log，確認 firmware 與 memory baseline。",
            "restore_memory_configuration",
            "完成核准的 seating／configuration 處理後重跑 memory test。",
            5,
            4,
        ),
        _p(
            "memory_recovers_cold_restart",
            "Cold restart 後記憶體容量恢復",
            "warm reboot 容量不對，完全斷電再開後 DIMM inventory 恢復",
            C.MEMORY_ERROR,
            ("warm reboot", "完全斷電", "dimm inventory", "容量不對"),
            ("warm-only issue", "cold restart recovers"),
            "比較 warm reboot 與 cold restart 的 DIMM inventory 和 BMC log。",
            "recover_memory_inventory",
            "記錄 power-state 相關現象並持續追蹤 firmware evidence。",
            4,
            2,
        ),
        _p(
            "nvme_inventory_missing",
            "NVMe 未出現在 inventory",
            "預期四顆 NVMe 但 inventory 只看到三顆",
            C.STORAGE_FAILURE,
            ("nvme", "只看到三顆", "inventory", "預期四顆"),
            ("one NVMe missing", "inventory mismatch"),
            "比對 approved storage inventory 與 firmware，再執行核准 A/B swap。",
            "restore_storage_path",
            "隔離 bay／cable／device path 並重跑 inventory test。",
            7,
            6,
        ),
        _p(
            "raid_virtual_disk_degraded",
            "RAID virtual disk degraded",
            "RAID 顯示 degraded，而且其中一顆 member disk 狀態異常",
            C.STORAGE_FAILURE,
            ("raid", "degraded", "member disk", "狀態異常"),
            ("virtual disk degraded", "member abnormal"),
            "先保存 controller log 並核對 approved RAID policy；不要直接 rebuild。",
            "restore_storage_path",
            "依核准程序處理 member path 後重新驗證 RAID 狀態。",
            5,
            4,
        ),
        _p(
            "storage_io_timeout",
            "Storage 壓力測試出現 I/O timeout",
            "磁碟都看得到，但 storage stress test 反覆出現 I/O timeout",
            C.STORAGE_FAILURE,
            ("磁碟都看得到", "stress test", "i/o timeout", "反覆"),
            ("inventory present", "I/O failure under load"),
            "核對 firmware／test baseline 並保存 controller 與 device error log。",
            "restore_storage_path",
            "完成核准的 storage path 隔離後重跑相同非生產資料測試。",
            4,
            3,
        ),
        _p(
            "pxe_fails_all_units",
            "同站所有機器 PXE 都失敗",
            "這個 station 換了 Golden Sample 還是 PXE boot failure",
            C.OS_BOOT_FAILURE,
            ("pxe", "golden sample", "boot failure", "station"),
            ("multiple DUTs", "same PXE station", "shared failure"),
            "用 Golden Sample 驗證 DHCP、image service 與 deployment profile。",
            "restore_pxe_path",
            "修復 PXE deployment path 後以相同 profile 重測。",
            6,
            5,
        ),
        _p(
            "no_boot_device_after_change",
            "變更設定後找不到 boot device",
            "修改 UEFI 設定後出現 no boot device，OS 進不去",
            C.OS_BOOT_FAILURE,
            ("uefi", "no boot device", "os 進不去", "修改"),
            ("post-configuration", "local boot target missing"),
            "比對 approved boot order、UEFI mode 與 image baseline。",
            "restore_boot_baseline",
            "恢復核准 boot configuration 後重新執行 boot test。",
            5,
            4,
        ),
        _p(
            "kernel_panic_after_image",
            "更新 image 後 kernel panic",
            "換成新的測試 image 後開機會 kernel panic，舊版可以",
            C.OS_BOOT_FAILURE,
            ("新的測試 image", "kernel panic", "舊版可以", "開機"),
            ("new image fails", "old baseline passes"),
            "核對 image checksum、kernel parameters 與 firmware compatibility。",
            "restore_boot_baseline",
            "恢復 approved image 或設定後保存 console log 並重測。",
            4,
            2,
        ),
    )


def match_case_patterns(problem: str, limit: int = 3) -> tuple[PatternMatch, ...]:
    if not isinstance(limit, int) or isinstance(limit, bool) or limit < 1:
        raise ValueError("limit must be a positive integer")
    normalized = problem.casefold()
    category = match_issue(problem).category
    matches = []
    for pattern in synthetic_case_patterns():
        terms = tuple(term for term in pattern.keywords if term.casefold() in normalized)
        score = min(1.0, (0.35 if pattern.symptom_category is category else 0.0) + 0.2 * len(terms))
        if score > 0:
            matches.append(PatternMatch(pattern, score, terms))
    return tuple(
        sorted(matches, key=lambda item: (-item.score, -item.pattern.case_count, item.pattern.id))[
            :limit
        ]
    )


def _p(
    id, title, problem, category, keywords, conditions, check, resolution, summary, cases, resolved
):
    return SyntheticCasePattern(
        id,
        title,
        problem,
        category,
        keywords,
        conditions,
        check,
        resolution,
        summary,
        cases,
        resolved,
    )
